apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # data is a key-value pairing. Can be anything
  # if value is meant to be a secret, needs to be turned into a base64 beforehand.
  mongo-root-username: dXNlcm5hbWU=                   #base64 version of "username"
  mongo-root-password: c3VwZXJzZWNyZXRwYXNzd29yZA==   #base64 version of "supersecretpassword"